spring:
  application:
    name: earthquake-app
  profiles:
    active: dev
  messages:
    basename: i18n/messages
    encoding: UTF-8

springdoc:
  swagger-ui:
    path: /swagger-ui.html


server:
  port: 8080