version: '3.8'

services:
  webapp:
    image: earthquake-app
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    networks:
      - backend
  mongodb:
    image: mongo:latest
    container_name: earthquake-app-db
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - 'MONGO_INITDB_DATABASE=earthquake'
    volumes:
      - mongodb_data:/data/db
    networks:
      backend:

networks:
  backend:

volumes:
  mongodb_data: