version: '3.8'

services:
  earthquake-app:
    image: earthquake-app-1
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/test
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:latest
    container_name: earthquake-app-db
    restart: always
    ports:
      - '27017:27017'
    environment:
      - 'MONGO_INITDB_DATABASE=test'
    volumes:
      - mongodb_data:/data/db
    networks:
      backend:

networks:
  backend:

volumes:
  mongodb_data:
